name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Org and Repo Secrets
        env:
          ORG_SECRET: ${{ secrets.ORG_HUSH }}
          REPO_SECRET: ${{ secrets.REPO_HUSH }}
        run: |
          import os
          print("ORG_SECRET:", os.getenv("ORG_SECRET"))
          print("REPO_SECRET:", os.getenv("REPO_SECRET"))
        shell: python
