name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set env as secret
        env:
          ORG_VAL: ${{ secrets.ORG_HUSH }}
          REPO_VAL: ${{ secrets.REPO_HUSH }}
        run: |
          import os
          for q in (os.getenv("ORG_VAL")):
            print(q)
        shell: python
